services:
  postgres:
    image: postgres:16.8
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      app_network:
    volumes:
      - redis_data:/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local